const PEOPLE = [
  { id: 1, imageUrl: "https://randomuser.me/api/portraits/men/1.jpg", answer: "Goy" },
  { id: 2, imageUrl: "https://randomuser.me/api/portraits/men/2.jpg", answer: "Goy" },
  { id: 3, imageUrl: "https://randomuser.me/api/portraits/men/3.jpg", answer: "Jew" },
  { id: 4, imageUrl: "https://randomuser.me/api/portraits/women/4.jpg", answer: "Goy" },
  { id: 5, imageUrl: "https://randomuser.me/api/portraits/men/5.jpg", answer: "Jew" },
  { id: 6, imageUrl: "https://randomuser.me/api/portraits/women/6.jpg", answer: "Jew" },
  { id: 7, imageUrl: "https://randomuser.me/api/portraits/men/7.jpg", answer: "Goy" },
  { id: 8, imageUrl: "https://randomuser.me/api/portraits/women/8.jpg", answer: "Goy" },
  { id: 9, imageUrl: "https://randomuser.me/api/portraits/men/9.jpg", answer: "Jew" },
  { id: 10, imageUrl: "https://randomuser.me/api/portraits/women/10.jpg", answer: "Goy" },
  { id: 11, imageUrl: "https://randomuser.me/api/portraits/men/11.jpg", answer: "Jew" },
  { id: 12, imageUrl: "https://randomuser.me/api/portraits/women/12.jpg", answer: "Jew" },
  { id: 13, imageUrl: "https://randomuser.me/api/portraits/men/13.jpg", answer: "Goy" },
  { id: 14, imageUrl: "https://randomuser.me/api/portraits/women/14.jpg", answer: "Goy" },
  { id: 15, imageUrl: "https://randomuser.me/api/portraits/men/15.jpg", answer: "Jew" },
  { id: 16, imageUrl: "https://randomuser.me/api/portraits/women/16.jpg", answer: "Goy" },
  { id: 17, imageUrl: "https://randomuser.me/api/portraits/men/17.jpg", answer: "Jew" },
  { id: 18, imageUrl: "https://randomuser.me/api/portraits/women/18.jpg", answer: "Jew" },
  { id: 19, imageUrl: "https://randomuser.me/api/portraits/men/19.jpg", answer: "Goy" },
  { id: 20, imageUrl: "https://randomuser.me/api/portraits/women/20.jpg", answer: "Goy" },
];
