// [name, "J" = Jew, "G" = Goy]
const _P = [
  // ── Actors / Actresses ──────────────────────────
  ["Adam Sandler","J"],
  ["Adrien Brody","J"],
  ["Alan Arkin","J"],
  ["Alyson Hannigan","J"],
  ["Andy Samberg","J"],
  ["Barbra Streisand","J"],
  ["Ben Stiller","J"],
  ["Billy Crystal","J"],
  ["Daniel Radcliffe","J"],
  ["David Schwimmer","J"],
  ["Debra Messing","J"],
  ["Dustin Hoffman","J"],
  ["Fran Drescher","J"],
  ["Gal Gadot","J"],
  ["Gene Wilder","J"],
  ["Goldie Hawn","J"],
  ["Harvey Keitel","J"],
  ["Jack Black","J"],
  ["Jake Gyllenhaal","J"],
  ["James Caan","J"],
  ["Jason Alexander","J"],
  ["Jeff Goldblum","J"],
  ["Jennifer Connelly","J"],
  ["Jerry Stiller","J"],
  ["Jesse Eisenberg","J"],
  ["Jonah Hill","J"],
  ["Joseph Gordon-Levitt","J"],
  ["Josh Gad","J"],
  ["Kirk Douglas","J"],
  ["Lisa Kudrow","J"],
  ["Mandy Patinkin","J"],
  ["Mayim Bialik","J"],
  ["Mel Brooks","J"],
  ["Mila Kunis","J"],
  ["Natalie Portman","J"],
  ["Paul Newman","J"],
  ["Paul Rudd","J"],
  ["Rachel Weisz","J"],
  ["Sacha Baron Cohen","J"],
  ["Sarah Michelle Gellar","J"],
  ["Sarah Silverman","J"],
  ["Scarlett Johansson","J"],
  ["Seth Rogen","J"],
  ["Winona Ryder","J"],
  ["Zach Braff","J"],
  ["Tom Hanks","G"],
  ["Tom Cruise","G"],
  ["Brad Pitt","G"],
  ["Leonardo DiCaprio","G"],
  ["Denzel Washington","G"],
  ["Will Smith","G"],
  ["Johnny Depp","G"],
  ["George Clooney","G"],
  ["Matt Damon","G"],
  ["Christian Bale","G"],
  ["Ryan Gosling","G"],
  ["Chris Hemsworth","G"],
  ["Chris Evans","G"],
  ["Robert De Niro","G"],
  ["Al Pacino","G"],
  ["Morgan Freeman","G"],
  ["Samuel L. Jackson","G"],
  ["Keanu Reeves","G"],
  ["Meryl Streep","G"],
  ["Cate Blanchett","G"],
  ["Nicole Kidman","G"],
  ["Julia Roberts","G"],
  ["Angelina Jolie","G"],
  ["Emma Stone","G"],
  ["Jennifer Lawrence","G"],
  ["Charlize Theron","G"],
  ["Anne Hathaway","G"],
  ["Reese Witherspoon","G"],
  ["Kate Winslet","G"],
  ["Viola Davis","G"],
  ["Halle Berry","G"],
  ["Sandra Bullock","G"],
  ["Hugh Jackman","G"],
  ["Benedict Cumberbatch","G"],
  ["Idris Elba","G"],
  ["Dwayne Johnson","G"],
  ["Sean Connery","G"],
  ["Anthony Hopkins","G"],
  ["Gary Oldman","G"],
  ["Colin Firth","G"],

  // ── Directors ───────────────────────────────────
  ["Steven Spielberg","J"],
  ["Stanley Kubrick","J"],
  ["Woody Allen","J"],
  ["Joel Coen","J"],
  ["Ethan Coen","J"],
  ["Roman Polanski","J"],
  ["Billy Wilder","J"],
  ["Judd Apatow","J"],
  ["J.J. Abrams","J"],
  ["Darren Aronofsky","J"],
  ["Sam Raimi","J"],
  ["Rob Reiner","J"],
  ["Martin Scorsese","G"],
  ["Francis Ford Coppola","G"],
  ["Quentin Tarantino","G"],
  ["Christopher Nolan","G"],
  ["Ridley Scott","G"],
  ["James Cameron","G"],
  ["Peter Jackson","G"],
  ["Alfred Hitchcock","G"],
  ["Clint Eastwood","G"],
  ["David Fincher","G"],
  ["Spike Lee","G"],
  ["George Lucas","G"],
  ["Tim Burton","G"],
  ["Denis Villeneuve","G"],

  // ── Comedians ───────────────────────────────────
  ["Larry David","J"],
  ["Jerry Seinfeld","J"],
  ["Joan Rivers","J"],
  ["Don Rickles","J"],
  ["Rodney Dangerfield","J"],
  ["George Burns","J"],
  ["Groucho Marx","J"],
  ["Lenny Bruce","J"],
  ["Carl Reiner","J"],
  ["Jon Stewart","J"],
  ["Amy Schumer","J"],
  ["Chelsea Handler","J"],
  ["Gilbert Gottfried","J"],
  ["Andy Kaufman","J"],
  ["Garry Shandling","J"],
  ["Richard Pryor","G"],
  ["Eddie Murphy","G"],
  ["Chris Rock","G"],
  ["Dave Chappelle","G"],
  ["Kevin Hart","G"],
  ["George Carlin","G"],
  ["Robin Williams","G"],
  ["Jim Carrey","G"],
  ["Steve Martin","G"],
  ["Bill Murray","G"],
  ["Rowan Atkinson","G"],
  ["Ricky Gervais","G"],
  ["Tina Fey","G"],

  // ── Musicians ───────────────────────────────────
  ["Bob Dylan","J"],
  ["Leonard Cohen","J"],
  ["Paul Simon","J"],
  ["Billy Joel","J"],
  ["Neil Diamond","J"],
  ["Gene Simmons","J"],
  ["Joey Ramone","J"],
  ["Amy Winehouse","J"],
  ["Drake","J"],
  ["Paula Abdul","J"],
  ["Adam Levine","J"],
  ["Leonard Bernstein","J"],
  ["George Gershwin","J"],
  ["Irving Berlin","J"],
  ["Burt Bacharach","J"],
  ["Carole King","J"],
  ["Lou Reed","J"],
  ["David Lee Roth","J"],
  ["Elvis Presley","G"],
  ["John Lennon","G"],
  ["Paul McCartney","G"],
  ["Mick Jagger","G"],
  ["Freddie Mercury","G"],
  ["David Bowie","G"],
  ["Michael Jackson","G"],
  ["Prince (musician)","G"],
  ["Elton John","G"],
  ["Bruce Springsteen","G"],
  ["Madonna (entertainer)","G"],
  ["Beyoncé","G"],
  ["Taylor Swift","G"],
  ["Adele","G"],
  ["Frank Sinatra","G"],
  ["Jimi Hendrix","G"],
  ["Bob Marley","G"],
  ["Whitney Houston","G"],
  ["Aretha Franklin","G"],
  ["Stevie Wonder","G"],
  ["Johnny Cash","G"],
  ["Kurt Cobain","G"],
  ["Dolly Parton","G"],
  ["Ed Sheeran","G"],

  // ── Business / Tech ─────────────────────────────
  ["Mark Zuckerberg","J"],
  ["Larry Page","J"],
  ["Sergey Brin","J"],
  ["Larry Ellison","J"],
  ["Michael Bloomberg","J"],
  ["George Soros","J"],
  ["Michael Dell","J"],
  ["Sheryl Sandberg","J"],
  ["Ralph Lauren","J"],
  ["Calvin Klein","J"],
  ["Marc Jacobs","J"],
  ["Estée Lauder","J"],
  ["Sam Altman","J"],
  ["Bob Iger","J"],
  ["Elon Musk","G"],
  ["Jeff Bezos","G"],
  ["Bill Gates","G"],
  ["Steve Jobs","G"],
  ["Warren Buffett","G"],
  ["Tim Cook","G"],
  ["Oprah Winfrey","G"],
  ["Richard Branson","G"],
  ["Jack Ma","G"],
  ["Henry Ford","G"],
  ["Walt Disney","G"],
  ["Rupert Murdoch","G"],

  // ── Politicians ─────────────────────────────────
  ["Bernie Sanders","J"],
  ["Chuck Schumer","J"],
  ["Henry Kissinger","J"],
  ["Rahm Emanuel","J"],
  ["Ruth Bader Ginsburg","J"],
  ["Benjamin Netanyahu","J"],
  ["Golda Meir","J"],
  ["David Ben-Gurion","J"],
  ["Yitzhak Rabin","J"],
  ["Shimon Peres","J"],
  ["Ariel Sharon","J"],
  ["Theodor Herzl","J"],
  ["Benjamin Disraeli","J"],
  ["Dianne Feinstein","J"],
  ["Joe Lieberman","J"],
  ["Barack Obama","G"],
  ["Donald Trump","G"],
  ["Joe Biden","G"],
  ["Bill Clinton","G"],
  ["George W. Bush","G"],
  ["Ronald Reagan","G"],
  ["John F. Kennedy","G"],
  ["Abraham Lincoln","G"],
  ["Franklin D. Roosevelt","G"],
  ["Winston Churchill","G"],
  ["Margaret Thatcher","G"],
  ["Angela Merkel","G"],
  ["Vladimir Putin","G"],
  ["Nelson Mandela","G"],
  ["Mahatma Gandhi","G"],
  ["Martin Luther King Jr.","G"],

  // ── Scientists ──────────────────────────────────
  ["Albert Einstein","J"],
  ["Richard Feynman","J"],
  ["J. Robert Oppenheimer","J"],
  ["John von Neumann","J"],
  ["Niels Bohr","J"],
  ["Jonas Salk","J"],
  ["Carl Sagan","J"],
  ["Emmy Noether","J"],
  ["Edward Teller","J"],
  ["Murray Gell-Mann","J"],
  ["Isaac Newton","G"],
  ["Charles Darwin","G"],
  ["Nikola Tesla","G"],
  ["Stephen Hawking","G"],
  ["Marie Curie","G"],
  ["Galileo Galilei","G"],
  ["Alan Turing","G"],
  ["Thomas Edison","G"],
  ["Neil deGrasse Tyson","G"],
  ["Max Planck","G"],

  // ── Writers / Intellectuals ─────────────────────
  ["Franz Kafka","J"],
  ["Philip Roth","J"],
  ["Isaac Asimov","J"],
  ["Arthur Miller","J"],
  ["Saul Bellow","J"],
  ["Noam Chomsky","J"],
  ["Ayn Rand","J"],
  ["Elie Wiesel","J"],
  ["Stan Lee","J"],
  ["Neil Gaiman","J"],
  ["Aaron Sorkin","J"],
  ["Sigmund Freud","J"],
  ["Hannah Arendt","J"],
  ["William Shakespeare","G"],
  ["Charles Dickens","G"],
  ["Mark Twain","G"],
  ["Ernest Hemingway","G"],
  ["George Orwell","G"],
  ["J.R.R. Tolkien","G"],
  ["Stephen King","G"],
  ["Jane Austen","G"],
  ["Edgar Allan Poe","G"],
  ["Leo Tolstoy","G"],
  ["Fyodor Dostoevsky","G"],
  ["Victor Hugo","G"],
  ["Toni Morrison","G"],
  ["Maya Angelou","G"],
  ["J.K. Rowling","G"],
  ["Agatha Christie","G"],

  // ── Athletes ────────────────────────────────────
  ["Sandy Koufax","J"],
  ["Mark Spitz","J"],
  ["Hank Greenberg","J"],
  ["Aly Raisman","J"],
  ["Michael Jordan","G"],
  ["LeBron James","G"],
  ["Muhammad Ali","G"],
  ["Pelé","G"],
  ["Serena Williams","G"],
  ["Usain Bolt","G"],
  ["Mike Tyson","G"],
  ["Lionel Messi","G"],
  ["Cristiano Ronaldo","G"],
  ["Tom Brady","G"],
  ["Michael Phelps","G"],
  ["Tiger Woods","G"],
  ["Babe Ruth","G"],
  ["Wayne Gretzky","G"],
  ["Roger Federer","G"],
  ["Simone Biles","G"],

  // ── Artists ─────────────────────────────────────
  ["Marc Chagall","J"],
  ["Mark Rothko","J"],
  ["Roy Lichtenstein","J"],
  ["Amedeo Modigliani","J"],
  ["Pablo Picasso","G"],
  ["Leonardo da Vinci","G"],
  ["Vincent van Gogh","G"],
  ["Claude Monet","G"],
  ["Salvador Dalí","G"],
  ["Frida Kahlo","G"],
  ["Andy Warhol","G"],
  ["Michelangelo","G"],
  ["Rembrandt","G"],

  // ── Media / TV ──────────────────────────────────
  ["Barbara Walters","J"],
  ["Larry King","J"],
  ["Wolf Blitzer","J"],
  ["Howard Stern","J"],
  ["Jake Tapper","J"],
  ["Ben Shapiro","J"],
  ["Lorne Michaels","J"],
  ["Anderson Cooper","G"],
  ["Oprah Winfrey","G"],
  ["David Letterman","G"],
  ["Johnny Carson","G"],
  ["Ellen DeGeneres","G"],
];

const PEOPLE = _P.map(([name, a], i) => ({
  id: i + 1,
  name,
  answer: a === "J" ? "Jew" : "Goy",
}));
